default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: discord_recruitment_bot_development

test:
  <<: *default
  database: discord_recruitment_bot_test

production:
  <<: *default
  database: discord_recruitment_bot_production
  password: <%= ENV['DATABASE_PASSWORD'] %>
