- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: apt upgrade
  become: yes
  apt:
    upgrade: 'yes'

- name: install apt-file
  become: yes
  apt:
    name: apt-file

- name: apt-file update
  become: yes
  shell: apt-file update

- name: install some libraries
  become: yes
  apt:
    name:
      - git
      - gem
      - zlib1g-dev
      - libsqlite3-dev
      - autoconf
      - libxml2-dev
      - libxslt1-dev
      - libmysqlclient-dev
      - software-properties-common
      - g++
      - gcc
      - make

- name: set original bashrc
  copy:
    src: ../files/bashrc
    dest: ~/.bashrc

# install libsodium for discordrb
- name: download libsodium
  get_url:
    url: https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
    dest: /tmp

- name: unarchieve libsodium
  unarchive:
    src: /tmp/LATEST.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure libsodium
  shell: cd /tmp/libsodium-stable && ./configure

- name: make libsodium
  shell: cd /tmp/libsodium-stable && make

- name: install libsodium
  become: yes
  shell: cd /tmp/libsodium-stable && make install
