name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # container:
    #   image: utyosu/build-rails:latest

    steps:
    - env:
        API_ENDPOINT: ${{ github.event.issue.pull_request.url }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH=`curl -X GET -H "Authorization: token ${GITHUB_TOKEN}" ${API_ENDPOINT} | jq -r '.head.ref'`
        echo $BRANCH
    # - run: |
    #     BRANCH_NAME=`echo "${GITHUB_REF}" | sed "s/^\(refs\/heads\/\|refs\/remotes\/\)//"`
    #     /app/run.sh https://github.com/${GITHUB_REPOSITORY}.git ${BRANCH_NAME} tools/cloud_build/test.sh
