# name: CI

# on: [push]

# jobs:
#   build:
#     name: Build and Publish

#     steps:
#     - uses: docker://docker.io/utyosu/build-rails:latest
#     - uses: actions/checkout@v1

#     - name: hoge
#       run: echo hogehoge

    # - name: install libraries
    #   run: sudo apt install -y libmysqlclient-dev

    # - name: install libsodium
    #   run: |
    #     wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz -O /tmp/LATEST.tar.gz
    #     tar zxvf /tmp/LATEST.tar.gz -C /tmp
    #     cd /tmp/libsodium-stable
    #     ./configure
    #     make
    #     sudo make install

    # - name: Set up Ruby
    #   uses: actions/setup-ruby@v1

    # - name: check ruby version
    #   run: ruby --version

    # - name: bundle install
    #   run: |
    #     gem install bundler
    #     bundle install --jobs 4

    # - name: setup database
    #   run: |
    #     bundle exec rails db:create
    #     bundle exec ridgepole -c config/database.yml --apply -f db/schema -E test

    # - name: exec rspec
    #   run: |
    #     bundle exec rspec
