name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: utyosu/build-rails:latest

    steps:
    - uses: actions/checkout@master
    - name: run test
      run: . tools/cloud_build/test.sh
