name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: utyosu/build-rails:latest

    steps:
    - uses: actions/checkout@master
    - run: |
        export PATH="/root/.rbenv/bin:/root/.rbenv/shims:$PATH"
        find /var/lib/mysql -type f -exec touch {} \;
        /app/run.sh https://github.com/${GITHUB_REPOSITORY}.git tools/cloud_build/test.sh
