name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: utyosu/build-rails:latest

    steps:
    - name: get branch name
      run: BRANCH_NAME=`echo "${GITHUB_REF}" | sed "s/^\(refs\/heads\/\|refs\/remotes\/\)//"`
    - run: /app/run.sh https://github.com/${GITHUB_REPOSITORY}.git ${BRANCH_NAME} tools/cloud_build/test.sh
