name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: utyosu/build-rails:latest

    steps:
    - uses: actions/checkout@master
    - name: run test
      run: |
        export PATH="/root/.rbenv/bin:/root/.rbenv/shims:$PATH"
        find /var/lib/mysql -type f -exec touch {} \;
        . tools/cloud_build/test.sh
