name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: utyosu/build-rails:latest

    steps:
    - run: echo ${GITHUB_REPOSITORY}
    - run: echo ${GITHUB_REF}
    - run: /app/run.sh https://github.com/${GITHUB_REPOSITORY}.git master tools/cloud_build/test.sh
